LunarLander-v2:
  n_envs: 1
  n_timesteps: !!float 1.5e6
  policy: 'MlpPolicy'
  normalize: "dict(norm_obs=True, norm_reward=False)"
  learning_rate: !!float 0.016
  n_delta: 12
  n_top: 6
  delta_std: 0.1
  policy_kwargs: "dict(net_arch=[12,12])"
  zero_policy: False