LunarLander-v2:
  n_envs: 1
  n_timesteps: !!float 1.5e6
  policy: 'MlpPolicy'
  normalize: "dict(norm_obs=True, norm_reward=False)"
  learning_rate: !!float 0.02
  n_delta: 10
  n_top: 3
  delta_std: 0.08
  policy_kwargs: "dict(net_arch=[20])"
  zero_policy: False