InvertedDoublePendulumBulletEnv-v0:
  batch_size: 256
  buffer_size: 200000
  gamma: 0.96
  gradient_steps: 2
  learning_rate: 0.003
  learning_starts: 10000
  n_timesteps: 100000.0
  noise_std: 0.2
  noise_type: normal
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[300])
  train_freq: 1
