InvertedDoublePendulumBulletEnv-v0:
  batch_size: 256
  buffer_size: 200000
  gamma: 0.98
  gradient_steps: 2
  learning_rate: 0.0007
  learning_starts: 10000
  n_timesteps: 100000.0
  noise_std: 0.05
  noise_type: normal
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[400, 400])
  train_freq: 1
