InvertedDoublePendulumBulletEnv-v0:
  batch_size: 256
  buffer_size: 200000
  gamma: 0.96
  gradient_steps: 2
  learning_rate: 0.00005
  learning_starts: 10000
  n_timesteps: 150000.0
  noise_std: 0.08
  noise_type: normal
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[600, 400, 300])
  train_freq: 1
